/**
 * 将 DB / 筛选器中的日文都道府県或短名映射为英文展示（英文站 UI）。
 * 匹配不到时回退原文。
 */
const JA_TO_EN: Record<string, string> = {
  All: "Nationwide",
  全国: "Nationwide",
  北海道: "Hokkaido",
  青森県: "Aomori",
  青森: "Aomori",
  岩手県: "Iwate",
  岩手: "Iwate",
  宮城県: "Miyagi",
  宮城: "Miyagi",
  秋田県: "Akita",
  秋田: "Akita",
  山形県: "Yamagata",
  山形: "Yamagata",
  福島県: "Fukushima",
  福島: "Fukushima",
  茨城県: "Ibaraki",
  茨城: "Ibaraki",
  栃木県: "Tochigi",
  栃木: "Tochigi",
  群馬県: "Gunma",
  群馬: "Gunma",
  埼玉県: "Saitama",
  埼玉: "Saitama",
  千葉県: "Chiba",
  千葉: "Chiba",
  東京都: "Tokyo",
  東京: "Tokyo",
  神奈川県: "Kanagawa",
  神奈川: "Kanagawa",
  新潟県: "Niigata",
  新潟: "Niigata",
  富山県: "Toyama",
  富山: "Toyama",
  石川県: "Ishikawa",
  石川: "Ishikawa",
  福井県: "Fukui",
  福井: "Fukui",
  山梨県: "Yamanashi",
  山梨: "Yamanashi",
  長野県: "Nagano",
  長野: "Nagano",
  岐阜県: "Gifu",
  岐阜: "Gifu",
  静岡県: "Shizuoka",
  静岡: "Shizuoka",
  愛知県: "Aichi",
  愛知: "Aichi",
  三重県: "Mie",
  三重: "Mie",
  滋賀県: "Shiga",
  滋賀: "Shiga",
  京都府: "Kyoto",
  京都: "Kyoto",
  大阪府: "Osaka",
  大阪: "Osaka",
  兵庫県: "Hyogo",
  兵庫: "Hyogo",
  奈良県: "Nara",
  奈良: "Nara",
  和歌山県: "Wakayama",
  和歌山: "Wakayama",
  鳥取県: "Tottori",
  鳥取: "Tottori",
  島根県: "Shimane",
  島根: "Shimane",
  岡山県: "Okayama",
  岡山: "Okayama",
  広島県: "Hiroshima",
  広島: "Hiroshima",
  山口県: "Yamaguchi",
  山口: "Yamaguchi",
  徳島県: "Tokushima",
  徳島: "Tokushima",
  香川県: "Kagawa",
  香川: "Kagawa",
  愛媛県: "Ehime",
  愛媛: "Ehime",
  高知県: "Kochi",
  高知: "Kochi",
  福岡県: "Fukuoka",
  福岡: "Fukuoka",
  佐賀県: "Saga",
  佐賀: "Saga",
  長崎県: "Nagasaki",
  長崎: "Nagasaki",
  熊本県: "Kumamoto",
  熊本: "Kumamoto",
  大分県: "Oita",
  大分: "Oita",
  宮崎県: "Miyazaki",
  宮崎: "Miyazaki",
  鹿児島県: "Kagoshima",
  鹿児島: "Kagoshima",
  沖縄県: "Okinawa",
  沖縄: "Okinawa",
};

export function regionDisplayForLocale(region: string, locale: string): string {
  if (locale !== "en") return region;
  const trimmed = region.trim();
  const direct = JA_TO_EN[trimmed];
  if (direct) return direct;
  const sortedKeys = Object.keys(JA_TO_EN).sort((a, b) => b.length - a.length);
  for (const ja of sortedKeys) {
    if (ja === "All" || ja === "全国") continue;
    if (trimmed.startsWith(ja)) return JA_TO_EN[ja]!;
  }
  return region;
}
